# ==============================================================================
# Simulation_Core/physics/iwm_disturbance.py
# Models the electromechanical disturbance force from In-Wheel Motors
# ==============================================================================
import numpy as np

def calculate_iwm_force(t, v_ms, wheel_radius=0.3):
    """
    Calculates the electromechanical disturbance force (F_em) generated by the
    rotor eccentricity of the In-Wheel Motor. This is a critical disturbance 
    ignored by the base paper.
    
    Args:
        t (float): Current time in seconds
        v_ms (float): Vehicle speed in meters/second
        wheel_radius (float): Radius of the tire (default 0.3m)
        
    Returns:
        float: Oscillating vertical disturbance force in Newtons
    """
    # Parameters from Karthick/Xu related IWM literature
    k_em = 15.0       # Electromechanical coupling factor (N/A)
    i_d = 20.0        # Stator current amplitude (A)
    p_pole = 8        # Number of pole pairs
    
    # Motor angular speed (rad/s) depends on vehicle speed and wheel radius
    # Assuming no slip for the disturbance calculation
    omega_m = v_ms / wheel_radius
    theta_m = omega_m * t
    
    # Oscillating vertical force due to IWM eccentricity
    # F_em(t) = k_em * i_d * sin(p * theta_m)
    f_em = k_em * i_d * np.sin(p_pole * theta_m)
    
    return f_em
