%% ========================================================================
% BUILD_BLOCKWISE_MODEL
% Regenerative LPV-Adaptive EV Active Suspension
% ONE SIMULINK BLOCK PER BLOCK OF THE SYSTEM DESIGN DIAGRAM
% ========================================================================
% Every block in the system design diagram exists here as a separate,
% named Simulink block, wired in the same order, with a written
% justification attached to the block (right-click > Block Parameters, or
% hover) and printed as an on-canvas annotation.
%
%   SYSTEM DESIGN BLOCK        SIMULINK BLOCK
%   -----------------------    --------------------------------
%   Road Profile               Road_Front / Road_Rear (From Workspace)
%   Summing junction           Sum_Junction
%   LPV Controller             LPV_Controller
%   EM Actuator                EM_Actuator
%   Half-Car Plant             HalfCar_Plant
%   Sensors and Estimator      Sensors_Estimator
%   TD3 Supervisor             TD3_Supervisor
%   Faraday Coil               Faraday_Coil
%   Rectifier                  Rectifier
%   Low Pass Filter            LC_Filter
%   Boost Converter            Boost_Converter
%   Battery                    Battery_SoC
%
% Two Unit Delay blocks (State_Delay, SoC_Delay) break the algebraic loops.
% They are a numerical necessity, not a modelling choice: a discrete-time
% feedback loop must contain at least one delay, and at 1 kHz a one-step
% delay also represents the real ECU compute latency.
%
% Run this INSTEAD of build_simulink_model.m when you need the block-wise
% model. Both use identical parameters and gains, so results match.
% ========================================================================
clear; clc; close all;
fprintf('======================================================================\n');
fprintf('[*] Building BLOCK-WISE Simulink model (one block per design block)\n');
fprintf('======================================================================\n');

%% ---------------- SECTION 1: PARAMETERS ----------------
p.ms = 730.0;  p.I_phi = 1222.0;  p.a = 1.1;  p.b = 1.5;
p.ms_f = p.ms*p.b/(p.a+p.b);  p.ms_r = p.ms*p.a/(p.a+p.b);
p.mu_f = 45.0;  p.mu_r = 45.0;
p.ks_f = 18000.0; p.ks_r = 22000.0; p.cs_f = 1200.0; p.cs_r = 1200.0;
p.kt_f = 190000.0; p.kt_r = 190000.0;
p.k_em = 15.0; p.i_d = 20.0; p.p_pole = 8; p.wheel_radius = 0.3;

% Electromagnetic transducer: C_e is DERIVED from k_e, never chosen.
p.k_e = 50.0; p.R_coil = 2.0; p.R_load = 10.0;
p.C_e = p.k_e^2/(p.R_coil + p.R_load);

p.stroke_max = 0.08; p.u_max = 6000.0; p.k_bs = 1e7;
p.V_diode = 0.7; p.L_filter = 0.01; p.C_filter = 0.0047;
p.D_boost = 0.60; p.eta_rect = 0.97; p.eta_boost = 0.92;
p.eta_act = 0.85; p.cap_batt_j = 50000.0;
p.dt = 0.001; p.T_total = 10.0; p.v_kmh = 72.0; p.v_ms = p.v_kmh/3.6;
p.sigma_mets = 0.1;
p.mode_dwell_s = 0.10; p.rho_hi = 0.35; p.rho_lo = 0.25;
p.kf_Q = 1e-3; p.kf_R = 5e-2; p.rho_rate_max = 4.0;

t = 0:p.dt:(p.T_total - p.dt);  n_steps = numel(t);
delay_steps = round((p.a+p.b)/p.v_ms/p.dt);
fprintf('[*] Parameters loaded. C_e = %.2f N.s/m (derived from k_e = %.1f)\n', p.C_e, p.k_e);

%% ---------------- SECTION 2: CARE GAIN SYNTHESIS ----------------
A_qc = [0, 1, 0, -1;
        -p.ks_f/p.ms_f, -p.cs_f/p.ms_f, 0, p.cs_f/p.ms_f;
        0, 0, 0, 1;
        p.ks_f/p.mu_f, p.cs_f/p.mu_f, -p.kt_f/p.mu_f, -p.cs_f/p.mu_f];
B_qc = [0; 1/p.ms_f; 0; -1/p.mu_f];
R_care = 1e-4;

Q_s = diag([5e5, 5e4, 1e4, 1e2]);
K_smooth = (1/R_care)*B_qc'*care_nt2(A_qc,B_qc,Q_s,R_care);  K_smooth = K_smooth(:)';
Q_r = diag([2.5e5, 3e5, 1e4, 1e2]);
K_rough  = (1/R_care)*B_qc'*care_nt2(A_qc,B_qc,Q_r,R_care);  K_rough  = K_rough(:)';
K_rho_dot = [0, 500, 0, 0];

fprintf('    K_smooth = [%.1f %.1f %.1f %.1f]\n', K_smooth);
fprintf('    K_rough  = [%.1f %.1f %.1f %.1f]\n', K_rough);
fprintf('    Vertex closed-loop max Re: %+.4f (rho=0), %+.4f (rho=1)\n', ...
    max(real(eig(A_qc-B_qc*K_smooth))), max(real(eig(A_qc-B_qc*K_rough))));

%% ---------------- SECTION 3: ROAD PROFILE ----------------
rng(42); alpha_r = 2*pi*0.01;
wamp = 2*pi*0.1*sqrt(16e-6*p.v_ms);  wn = randn(1,n_steps);  w_f = zeros(1,n_steps);
for i = 2:n_steps, w_f(i) = w_f(i-1) + p.dt*(-alpha_r*w_f(i-1) + wamp*wn(i-1)); end
rng(43); wampD = 2*pi*0.1*sqrt(1024e-6*p.v_ms);
wnD = randn(1,n_steps); ov = zeros(1,n_steps);
for i = 2:n_steps, ov(i) = ov(i-1) + p.dt*(-alpha_r*ov(i-1) + wampD*wnD(i-1)); end
i_s = round(3/p.dt)+1; i_e = round(7/p.dt); fl = round(0.2/p.dt);
fade = ones(1,i_e-i_s+1); fade(1:fl) = linspace(0,1,fl); fade(end-fl+1:end) = linspace(1,0,fl);
w_f(i_s:i_e) = w_f(i_s:i_e) + ov(i_s:i_e).*fade;
depths = [-0.06 -0.04 -0.02 -0.005 -0.05 -0.03];
widths = [0.25 0.15 0.10 0.05 0.20 0.12];
rng(42); times = linspace(3.5,6.5,6); times = times(randperm(6));
for k = 1:6
    st = round(times(k)/p.dt)+1; du = round(widths(k)/p.dt);
    en = min(st+du-1, n_steps); xp = linspace(0,2*pi,en-st+1);
    w_f(st:en) = w_f(st:en) + (depths(k)/2)*(1-cos(xp));
end
w_r = zeros(1,n_steps); w_r(delay_steps+1:end) = w_f(1:end-delay_steps);
assignin('base','road_f_ts', timeseries(w_f', t'));
assignin('base','road_r_ts', timeseries(w_r', t'));
fprintf('[*] Road profile generated and exported to workspace.\n');

%% ---------------- SECTION 4: BUILD THE BLOCK-WISE MODEL ----------------
model = 'Suspension_BlockDesign';
script_dir = fileparts(mfilename('fullpath'));
slx_path = fullfile(script_dir, [model '.slx']);

if bdIsLoaded(model), close_system(model, 0); end
if exist(slx_path,'file'), delete(slx_path); end

new_system(model); open_system(model);
set_param(model, 'SolverType','Fixed-step', 'Solver','FixedStepDiscrete', ...
                 'FixedStep', num2str(p.dt), 'StopTime', num2str(p.T_total), ...
                 'SaveOutput','on', 'OutputSaveName','sim_yout');

B = @(n) [model '/' n];

% ---- SOURCES ----
add_block('simulink/Sources/Clock', B('t_clock'), 'Position',[30 470 60 500]);
add_block('simulink/Sources/From Workspace', B('Road_Front'), ...
    'VariableName','road_f_ts','Interpolate','on','Position',[30 100 150 140]);
add_block('simulink/Sources/From Workspace', B('Road_Rear'), ...
    'VariableName','road_r_ts','Interpolate','on','Position',[30 160 150 200]);

% ---- SUMMING JUNCTION ----
% Reference is zero: this is a REGULATOR, not a tracker. The junction forms
% e = 0 - x_hat, making the negative-feedback structure explicit.
add_block('simulink/Sources/Constant', B('Reference'), ...
    'Value','zeros(8,1)','Position',[190 300 250 330]);
add_block('simulink/Math Operations/Sum', B('Sum_Junction'), ...
    'Inputs','+-','IconShape','round','Position',[290 295 320 325]);

% ---- FUNCTIONAL BLOCKS (one per system-design block) ----
mkfun(B('LPV_Controller'),   [370 280 510 350]);
mkfun(B('EM_Actuator'),      [560 280 690 350]);
mkfun(B('HalfCar_Plant'),    [740 270 890 360]);
mkfun(B('Sensors_Estimator'),[740 430 890 500]);
mkfun(B('TD3_Supervisor'),   [520 430 660 500]);
mkfun(B('Faraday_Coil'),     [740 580 890 650]);
mkfun(B('Rectifier'),        [560 580 690 650]);
mkfun(B('LC_Filter'),        [380 580 510 650]);
mkfun(B('Boost_Converter'),  [200 580 330 650]);
mkfun(B('Battery_SoC'),      [30 580 150 650]);

% ---- DELAYS (break the algebraic loops) ----
add_block('simulink/Discrete/Unit Delay', B('State_Delay'), ...
    'InitialCondition','zeros(8,1)','SampleTime',num2str(p.dt), ...
    'Position',[940 305 980 335]);
add_block('simulink/Discrete/Unit Delay', B('SoC_Delay'), ...
    'InitialCondition','0.5','SampleTime',num2str(p.dt), ...
    'Position',[430 700 470 730]);

% ---- SCOPES ----
add_block('simulink/Sinks/Scope', B('Sc_BodyAccel'), 'Position',[960 180 1000 210],'Open','off');
add_block('simulink/Sinks/Scope', B('Sc_Force'),     'Position',[960 400 1000 430],'Open','off');
add_block('simulink/Sinks/Scope', B('Sc_Rho'),       'Position',[960 500 1000 530],'Open','off');
add_block('simulink/Sinks/Scope', B('Sc_SoC'),       'Position',[ 60 700 100  730],'Open','off');
add_block('simulink/Sinks/Scope', B('Sc_Power'),     'Position',[240 700 280  730],'Open','off');

fprintf('[*] Blocks placed. Injecting code and justifications...\n');

%% ---------------- SECTION 5: BLOCK CODE + JUSTIFICATIONS ----------------
J = containers.Map();

J('HalfCar_Plant') = [ ...
 'PURPOSE: The physical vehicle. Converts actuator force and road input into body and wheel motion.' newline ...
 'JUSTIFICATION: This is the plant being controlled. A 4-DOF half-car is the minimum model that ' ...
 'captures BOTH heave and pitch; a quarter-car cannot represent pitch, which is a primary ride-comfort ' ...
 'complaint. Includes cubic bump stops (hard travel limits) and the in-wheel-motor electromagnetic ' ...
 'disturbance, both of which are real effects for an IWM EV.' newline ...
 'EQUATIONS:' newline ...
 '  m_s*z_c_ddot   = -(F_sf + F_sr)' newline ...
 '  I_phi*th_ddot  = a*F_sf - b*F_sr' newline ...
 '  m_uf*z_uf_ddot = F_sf - k_tf*(z_uf - w_f) + F_iwm' newline ...
 '  F_s = k_s*def + c_s*v_rel + F_bumpstop - u_actuator' newline ...
 'INTEGRATION: RK4, fixed step 1 ms.'];

J('Sensors_Estimator') = [ ...
 'PURPOSE: Produces the state estimate and the road-severity scheduling parameter.' newline ...
 'JUSTIFICATION: Not all 8 states are measurable on a real vehicle, so the controller cannot be given ' ...
 'the true state. This block also supplies rho, the LPV scheduling parameter. A scalar Kalman filter ' ...
 'is used because it weights the measurement by its covariance instead of applying a fixed lag. ' ...
 'The RATE LIMIT on rho is essential, not cosmetic: polytopic gain scheduling is only justified when ' ...
 'the scheduling parameter varies within a bound (see stability note in LPV_Controller).' newline ...
 'ALSO CONTAINS: event-triggered transmission filter, which only forwards the state when ' ...
 '||e|| > sigma*||x||, reducing network load.'];

J('TD3_Supervisor') = [ ...
 'PURPOSE: Decides COMFORT (actuator motors) vs ECO (actuator harvests).' newline ...
 'JUSTIFICATION: The actuator cannot simultaneously inject and recover energy, so an arbitration ' ...
 'policy is required. Decision uses road severity, its rate, and battery state of charge.' newline ...
 'HYSTERESIS + DWELL TIME: a bare threshold test toggles at ~300 Hz, and every toggle is a step ' ...
 'discontinuity in actuator force that injects spurious body acceleration. A Schmitt-trigger band ' ...
 '(rho_lo=0.25, rho_hi=0.35) plus a 100 ms minimum hold makes the policy implementable on a real ECU.'];

J('LPV_Controller') = [ ...
 'PURPOSE: Computes the active control force by scheduling between two vertex gains.' newline ...
 'JUSTIFICATION: A single fixed gain cannot be optimal on both smooth and broken road. Two LQR gains ' ...
 'are synthesised from the Continuous Algebraic Riccati Equation at the extremes of road severity and ' ...
 'blended: K(rho) = (1-rho)*K_smooth + rho*K_rough.' newline ...
 'STABILITY (state this honestly): both vertex closed loops are Hurwitz, so the loop is stable for ' ...
 'every FROZEN rho. A numerical LMI search finds NO common quadratic Lyapunov matrix for these two ' ...
 'vertices, so stability under arbitrarily fast rho variation is NOT proven. This is why rho is rate ' ...
 'limited in Sensors_Estimator - the rate bound is what makes the design sound.' newline ...
 'ALSO: feedforward term on rho_dot pre-stiffens the suspension as the road worsens.'];

J('EM_Actuator') = [ ...
 'PURPOSE: The electromagnetic actuator. Applies force to the suspension.' newline ...
 'JUSTIFICATION: This is a TWO-PORT device - the same coil that produces force also generates ' ...
 'voltage. It is modelled as one block for that reason.' newline ...
 '  COMFORT mode: applies the LPV command, limited to +/- 6 kN (real actuators saturate).' newline ...
 '  ECO mode: applies the Lenz reaction force F = k_e*i = C_e*v_rel, opposing motion.' newline ...
 'IMPORTANT: the ECO force uses RELATIVE velocity (body minus wheel), not absolute body velocity. ' ...
 'A force proportional to absolute velocity is a skyhook force, which a two-terminal electromagnetic ' ...
 'damper physically cannot produce.'];

J('Faraday_Coil') = [ ...
 'PURPOSE: Generates back-EMF from suspension motion. This is where energy recovery begins.' newline ...
 'JUSTIFICATION: Faraday law of induction - relative motion between coil and magnet induces voltage:' newline ...
 '  e = k_e * v_rel' newline ...
 'CRITICAL COUPLING: the regenerative damping is NOT a free parameter. Since the same k_e governs ' ...
 'both generation and the Lenz reaction force:' newline ...
 '  i = e/(R_coil + R_load),   F = k_e*i   =>   C_e = k_e^2/(R_coil + R_load)' newline ...
 'This makes energy conservation STRUCTURAL rather than enforced by clamping:' newline ...
 '  P_elec/P_mech = R_load/(R_coil + R_load) < 1  ALWAYS.'];

J('Rectifier') = [ ...
 'PURPOSE: Converts the alternating back-EMF into unidirectional DC.' newline ...
 'JUSTIFICATION: Suspension motion alternates in direction, so the induced EMF alternates in sign. ' ...
 'A battery can only be charged with DC, so rectification is mandatory. Modelled as a full-bridge ' ...
 'rectifier: output = |e| - 2*V_diode, since current passes through two conducting diodes.'];

J('LC_Filter') = [ ...
 'PURPOSE: Smooths the rectified voltage into usable DC. Includes the capacitor bank.' newline ...
 'JUSTIFICATION: Rectified output is a pulsating waveform. Feeding it directly to a battery causes ' ...
 'ripple current and reduces life. An LC low-pass filter (L = 10 mH, C = 4700 uF) attenuates ripple.' newline ...
 'NUMERICS: integrated with SEMI-IMPLICIT (symplectic) Euler. This LC is lightly damped (zeta ~ 0.07) ' ...
 'and forward Euler is unconditionally unstable for such a system - it was the reason the earlier ' ...
 'version needed hard clamps on current and voltage. Semi-implicit Euler is stable at 1 ms.'];

J('Boost_Converter') = [ ...
 'PURPOSE: Steps the filtered voltage up to the DC bus / battery level.' newline ...
 'JUSTIFICATION: Energy recovered from a single pothole is small and arrives at low voltage - below ' ...
 'the battery terminal voltage, so it cannot charge the battery directly. A boost converter raises it:' newline ...
 '  V_out = V_in/(1 - D),  D = 0.6' newline ...
 'A converter raises VOLTAGE but cannot create POWER, so power is scaled only by its efficiency (0.92).'];

J('Battery_SoC') = [ ...
 'PURPOSE: Tracks battery state of charge, and closes the loop back to the supervisor.' newline ...
 'JUSTIFICATION: The supervisor needs to know how much energy is available before deciding whether ' ...
 'the actuator may spend it. SoC is integrated by coulomb counting:' newline ...
 '  SoC(t) = SoC_0 + integral( P_net / E_capacity ) dt' newline ...
 'Charges in ECO mode from the boost converter, discharges in COMFORT mode through actuator work ' ...
 'divided by actuator efficiency.'];

% ---- Generate and inject each block's code ----
blocks = {'LPV_Controller','EM_Actuator','HalfCar_Plant','Sensors_Estimator', ...
          'TD3_Supervisor','Faraday_Coil','Rectifier','LC_Filter', ...
          'Boost_Converter','Battery_SoC'};
codes = struct();
codes.HalfCar_Plant     = code_plant(p);
codes.Sensors_Estimator = code_estimator(p);
codes.TD3_Supervisor    = code_supervisor(p);
codes.LPV_Controller    = code_lpv(p, K_smooth, K_rough, K_rho_dot);
codes.EM_Actuator       = code_actuator(p);
codes.Faraday_Coil      = code_coil(p);
codes.Rectifier         = code_rectifier(p);
codes.LC_Filter         = code_lcfilter(p);
codes.Boost_Converter   = code_boost(p);
codes.Battery_SoC       = code_battery(p);

n_ok = 0;
for k = 1:numel(blocks)
    nm = blocks{k};
    set_param(B(nm), 'Description', J(nm));          % justification on the block
    if inject_code(model, nm, codes.(nm)), n_ok = n_ok + 1; end
end
fprintf('    [+] %d/%d block scripts injected.\n', n_ok, numel(blocks));
if n_ok < numel(blocks)
    outdir = fullfile(script_dir,'block_code');
    if ~exist(outdir,'dir'), mkdir(outdir); end
    for k = 1:numel(blocks)
        fid = fopen(fullfile(outdir,[blocks{k} '.m']),'w');
        fprintf(fid,'%s',codes.(blocks{k})); fclose(fid);
    end
    fprintf('    [!] Auto-inject incomplete. Code written to scripts/block_code/\n');
    fprintf('    [!] Open each block and paste the matching file.\n');
end

%% ---------------- SECTION 6: WIRING ----------------
L = @(a,b) add_line(model, a, b, 'autorouting','on');

L('Reference/1','Sum_Junction/1');               % reference = 0 (regulator)
L('Sensors_Estimator/1','Sum_Junction/2');       % negative feedback of x_hat
L('Sum_Junction/1','LPV_Controller/1');          % err = 0 - x_hat
L('Sensors_Estimator/2','LPV_Controller/2');     % rho
L('Sensors_Estimator/3','LPV_Controller/3');     % rho_dot
L('TD3_Supervisor/1','LPV_Controller/4');        % mode

L('LPV_Controller/1','EM_Actuator/1');          % u_cmd_f
L('LPV_Controller/2','EM_Actuator/2');          % u_cmd_r
L('TD3_Supervisor/1','EM_Actuator/3');          % mode
L('State_Delay/1','EM_Actuator/4');             % delayed state (for v_rel)

L('t_clock/1','HalfCar_Plant/1');
L('Road_Front/1','HalfCar_Plant/2');
L('Road_Rear/1','HalfCar_Plant/3');
L('EM_Actuator/1','HalfCar_Plant/4');           % u_f
L('EM_Actuator/2','HalfCar_Plant/5');           % u_r

L('HalfCar_Plant/1','State_Delay/1');           % x -> delay
L('HalfCar_Plant/2','Sc_BodyAccel/1');          % body acceleration
L('EM_Actuator/1','Sc_Force/1');

L('State_Delay/1','Sensors_Estimator/1');
L('Sensors_Estimator/2','Sc_Rho/1');

L('Sensors_Estimator/2','TD3_Supervisor/1');    % rho
L('Sensors_Estimator/3','TD3_Supervisor/2');    % rho_dot
L('SoC_Delay/1','TD3_Supervisor/3');            % soc

L('State_Delay/1','Faraday_Coil/1');
L('TD3_Supervisor/1','Faraday_Coil/2');
L('Faraday_Coil/1','Rectifier/1');              % emf
L('Rectifier/1','LC_Filter/1');                 % v_rect
L('TD3_Supervisor/1','LC_Filter/2');
L('LC_Filter/1','Boost_Converter/1');           % v_cap
L('Rectifier/2','Boost_Converter/2');           % i_coil
L('Faraday_Coil/2','Boost_Converter/3');        % p_mech (conservation bound)
L('Boost_Converter/2','Sc_Power/1');            % p_out

L('Boost_Converter/2','Battery_SoC/1');         % p_out
L('EM_Actuator/1','Battery_SoC/2');             % u_f
L('State_Delay/1','Battery_SoC/3');
L('TD3_Supervisor/1','Battery_SoC/4');
L('Battery_SoC/1','SoC_Delay/1');
L('Battery_SoC/1','Sc_SoC/1');

% Terminate the diagnostic outputs that are not consumed downstream.
% Simulink requires every output port to be connected.
add_block('simulink/Sinks/Terminator', B('Term_iL'),   'Position',[540 700 560 720]);
add_block('simulink/Sinks/Terminator', B('Term_vbus'), 'Position',[350 700 370 720]);
L('LC_Filter/2','Term_iL/1');                   % inductor current (diagnostic)
L('Boost_Converter/1','Term_vbus/1');           % DC bus voltage (diagnostic)

fprintf('[*] Wiring complete.\n');

%% ---------------- SECTION 7: ON-CANVAS ANNOTATIONS ----------------
note(model,'SYSTEM DESIGN: Road -> Controller -> Actuator -> Plant -> Output.  Feedback via Sensors/Estimator.  Energy branch along the bottom.',[30 30 900 55]);
note(model,'REGULATOR: reference is zero. The task is disturbance rejection, not tracking.',[190 250 520 272]);
note(model,'TWO-PORT DEVICE: EM_Actuator and Faraday_Coil are the SAME physical coil. C_e = k_e^2/(R_coil+R_load) links them.',[560 380 900 410]);
note(model,'ENERGY RECOVERY CHAIN (right to left): Coil -> Rectifier -> LC Filter -> Boost -> Battery',[30 545 900 570]);
note(model,'Unit Delays break the algebraic loops and represent one-step ECU compute latency.',[930 350 1010 400]);

set_param(model,'ZoomFactor','FitSystem');
save_system(model, slx_path);
fprintf('\n[*] SAVED: %s\n', slx_path);
fprintf('[*] Open it, then press PLAY. Right-click any block > Block Parameters\n');
fprintf('    to read that block''s justification.\n');
fprintf('======================================================================\n');


%% ======================== LOCAL HELPER FUNCTIONS ========================
function mkfun(path_, pos)
    add_block('simulink/User-Defined Functions/MATLAB Function', path_, 'Position', pos);
end

function note(model, txt, pos)
% Add an on-canvas annotation. The annotation API differs across releases,
% so try the modern object API first and fall back to the legacy block.
% Annotations are cosmetic - never let them abort the build.
    try
        an = Simulink.Annotation([model '/' txt(1:min(24,end))]);
        an.position = pos;
        an.FontSize = 10;
    catch
        try
            h = add_block('built-in/Note', ...
                [model '/note' num2str(randi(1e9))], 'Position', pos);
            set_param(h, 'Text', txt, 'FontSize','10');
        catch
            % Annotation unsupported on this release - skip silently.
        end
    end
end

function ok = inject_code(model, blockname, code)
    ok = false;
    try
        rt = sfroot();
        ch = rt.find('-isa','Stateflow.EMChart');
        tgt = [model '/' blockname];
        for i = 1:numel(ch)
            if strcmp(ch(i).Path, tgt)
                ch(i).Script = code; ok = true; return;
            end
        end
    catch
        ok = false;
    end
end

function P = care_nt2(A,B,Q,R)
    n = size(A,1); H = [A, -B*(1/R)*B'; -Q, -A'];
    [V,D] = eig(H); ev = diag(D);
    [~,ix] = sort(real(ev)); V = V(:,ix);
    X1 = V(1:n,1:n); X2 = V(n+1:end,1:n);
    P = real(X2/X1); P = (P+P')/2;
end

%% ---- Per-block code generators ----
function c = code_plant(p)
c = sprintf([ ...
'function [x_out, accel] = HalfCar_Plant(t_in, w_f, w_r, u_f, u_r)\n' ...
'%%#codegen\n' ...
'%% 4-DOF half-car plant. RK4, fixed step. See block Description for justification.\n' ...
'persistent x\n' ...
'ms=%.4f; Ip=%.4f; a=%.4f; b=%.4f; muf=%.4f; mur=%.4f;\n' ...
'ksf=%.2f; ksr=%.2f; csf=%.2f; csr=%.2f; ktf=%.2f; ktr=%.2f;\n' ...
'kem=%.4f; idc=%.4f; pp=%d; whr=%.4f; vms=%.4f;\n' ...
'sm=%.6f; kbs=%.6e; dt=%.6f;\n' ...
'if isempty(x) || t_in < dt/2\n' ...
'    x = zeros(8,1);\n' ...
'end\n' ...
'k1 = ode_(t_in,      x,          u_f,u_r,w_f,w_r,ms,Ip,a,b,muf,mur,ksf,ksr,csf,csr,ktf,ktr,kem,idc,pp,whr,vms,sm,kbs);\n' ...
'k2 = ode_(t_in+dt/2, x+k1*dt/2,  u_f,u_r,w_f,w_r,ms,Ip,a,b,muf,mur,ksf,ksr,csf,csr,ktf,ktr,kem,idc,pp,whr,vms,sm,kbs);\n' ...
'k3 = ode_(t_in+dt/2, x+k2*dt/2,  u_f,u_r,w_f,w_r,ms,Ip,a,b,muf,mur,ksf,ksr,csf,csr,ktf,ktr,kem,idc,pp,whr,vms,sm,kbs);\n' ...
'k4 = ode_(t_in+dt,   x+k3*dt,    u_f,u_r,w_f,w_r,ms,Ip,a,b,muf,mur,ksf,ksr,csf,csr,ktf,ktr,kem,idc,pp,whr,vms,sm,kbs);\n' ...
'x = x + (dt/6)*(k1 + 2*k2 + 2*k3 + k4);\n' ...
'x_out = x;\n' ...
'accel = k1(5);\n' ...
'end\n\n' ...
'function dx = ode_(t,x,uf,ur,wf,wr,ms,Ip,a,b,muf,mur,ksf,ksr,csf,csr,ktf,ktr,kem,idc,pp,whr,vms,sm,kbs)\n' ...
'zc=x(1); th=x(2); zuf=x(3); zur=x(4); zcd=x(5); thd=x(6); zufd=x(7); zurd=x(8);\n' ...
'zsf=zc-a*th; zsr=zc+b*th; zsfd=zcd-a*thd; zsrd=zcd+b*thd;\n' ...
'dsf=zsf-zuf; dsr=zsr-zur; dtf=zuf-wf; dtr=zur-wr;\n' ...
'vrf=zsfd-zufd; vrr=zsrd-zurd;\n' ...
'if dsf> sm; fbf=kbs*(dsf-sm)^3; elseif dsf<-sm; fbf=kbs*(dsf+sm)^3; else; fbf=0; end\n' ...
'if dsr> sm; fbr=kbs*(dsr-sm)^3; elseif dsr<-sm; fbr=kbs*(dsr+sm)^3; else; fbr=0; end\n' ...
'fi = kem*idc*sin(pp*(vms/whr)*t);\n' ...
'Fsf = ksf*dsf + csf*vrf + fbf - uf;\n' ...
'Fsr = ksr*dsr + csr*vrr + fbr - ur;\n' ...
'dx = [zcd; thd; zufd; zurd; -(Fsf+Fsr)/ms; (a*Fsf-b*Fsr)/Ip; (Fsf-ktf*dtf+fi)/muf; (Fsr-ktr*dtr+fi)/mur];\n' ...
'end\n'], p.ms,p.I_phi,p.a,p.b,p.mu_f,p.mu_r,p.ks_f,p.ks_r,p.cs_f,p.cs_r, ...
   p.kt_f,p.kt_r,p.k_em,p.i_d,p.p_pole,p.wheel_radius,p.v_ms,p.stroke_max,p.k_bs,p.dt);
end

function c = code_estimator(p)
c = sprintf([ ...
'function [x_hat, rho, rho_dot] = Sensors_Estimator(x_in)\n' ...
'%%#codegen\n' ...
'%% Event-triggered transmission + scalar Kalman road estimator + RATE LIMIT.\n' ...
'persistent xk first rho_p rdot kfP\n' ...
'a=%.4f; sig=%.4f; wmax=%.4f; dt=%.6f; ema=%.4f;\n' ...
'kfQ=%.6f; kfR=%.6f; rate_max=%.4f;\n' ...
'if isempty(first)\n' ...
'    xk = zeros(8,1); first = false; rho_p = 0; rdot = 0; kfP = 1;\n' ...
'end\n' ...
'e = x_in - xk;\n' ...
'if norm(e) > sig*norm(x_in)\n' ...
'    xk = x_in;\n' ...
'end\n' ...
'x_hat = xk;\n' ...
'rho_meas = min(1, max(0, abs(x_in(1) - a*x_in(2) - x_in(3))/wmax));\n' ...
'kfP = kfP + kfQ;\n' ...
'kfK = kfP/(kfP + kfR);\n' ...
'rho_raw = rho_p + kfK*(rho_meas - rho_p);\n' ...
'kfP = (1 - kfK)*kfP;\n' ...
'dmax = rate_max*dt;\n' ...
'rho = min(rho_p + dmax, max(rho_p - dmax, rho_raw));\n' ...
'rho = min(1, max(0, rho));\n' ...
'rdot = ema*((rho - rho_p)/dt) + (1-ema)*rdot;\n' ...
'rho_dot = rdot;\n' ...
'rho_p = rho;\n' ...
'end\n'], p.a, p.sigma_mets, 0.05, p.dt, 0.05, p.kf_Q, p.kf_R, p.rho_rate_max);
end

function c = code_supervisor(p)
c = sprintf([ ...
'function mode = TD3_Supervisor(rho, rho_dot, soc)\n' ...
'%%#codegen\n' ...
'%% Hysteresis + minimum dwell time. Prevents ~300 Hz mode chatter.\n' ...
'persistent mprev dcnt\n' ...
'dwell_n=%d; rho_hi=%.4f; rho_lo=%.4f;\n' ...
'if isempty(mprev)\n' ...
'    mprev = 1; dcnt = dwell_n;\n' ...
'end\n' ...
'req = mprev;\n' ...
'if mprev == 1\n' ...
'    if rho > rho_hi || rho_dot > 0.5; req = 0; end\n' ...
'else\n' ...
'    if rho < rho_lo && rho_dot < 0.5; req = 1; end\n' ...
'end\n' ...
'if soc < 0.02\n' ...
'    req = 1;\n' ...
'elseif soc < 0.25 && rho < 0.7\n' ...
'    req = 1;\n' ...
'end\n' ...
'if req ~= mprev && dcnt >= dwell_n\n' ...
'    m = req; dcnt = 0;\n' ...
'else\n' ...
'    m = mprev; dcnt = dcnt + 1;\n' ...
'end\n' ...
'mprev = m;\n' ...
'mode = double(m);\n' ...
'end\n'], round(p.mode_dwell_s/p.dt), p.rho_hi, p.rho_lo);
end

function c = code_lpv(p, Ks, Kr, Krd)
c = sprintf([ ...
'function [u_cmd_f, u_cmd_r] = LPV_Controller(err, rho, rho_dot, mode)\n' ...
'%%#codegen\n' ...
'%% Polytopic gain scheduling between two CARE vertex gains + rho_dot feedforward.\n' ...
'%% err = 0 - x_hat from the summing junction (regulator: reference is zero).\n' ...
'a=%.4f; b=%.4f; umax=%.4f;\n' ...
'Ks = [%s];\n' ...
'Kr = [%s];\n' ...
'Krd = [%s];\n' ...
'xh = -err;   %% recover the estimated state from the error signal\n' ...
'zsf = xh(1) - a*xh(2); zsfd = xh(5) - a*xh(6);\n' ...
'qcf = [zsf - xh(3); zsfd; 0; xh(7)];\n' ...
'zsr = xh(1) + b*xh(2); zsrd = xh(5) + b*xh(6);\n' ...
'qcr = [zsr - xh(4); zsrd; 0; xh(8)];\n' ...
'if mode > 0.5\n' ...
'    u_cmd_f = 0; u_cmd_r = 0;   %% ECO: force comes from the coil reaction\n' ...
'else\n' ...
'    Kf = (1-rho)*Ks + rho*Kr;\n' ...
'    ffl = 0.2*umax;\n' ...
'    u_cmd_f = -Kf*qcf + max(-ffl, min(ffl, -Krd*max(0,rho_dot)*qcf));\n' ...
'    u_cmd_r = -Kf*qcr + max(-ffl, min(ffl, -Krd*max(0,rho_dot)*qcr));\n' ...
'end\n' ...
'end\n'], p.a, p.b, p.u_max, num2str(Ks,'%.6f '), num2str(Kr,'%.6f '), num2str(Krd,'%.6f '));
end

function c = code_actuator(p)
c = sprintf([ ...
'function [u_f, u_r] = EM_Actuator(u_cmd_f, u_cmd_r, mode, x_d)\n' ...
'%%#codegen\n' ...
'%% Two-port electromagnetic actuator. Motors in COMFORT, generates in ECO.\n' ...
'a=%.4f; b=%.4f; umax=%.4f; C_e=%.6f;\n' ...
'vrf = (x_d(5) - a*x_d(6)) - x_d(7);\n' ...
'vrr = (x_d(5) + b*x_d(6)) - x_d(8);\n' ...
'if mode > 0.5\n' ...
'    %% ECO: Lenz reaction force, driven by RELATIVE velocity (not skyhook)\n' ...
'    u_f = -C_e*vrf;\n' ...
'    u_r = -C_e*vrr;\n' ...
'else\n' ...
'    u_f = u_cmd_f;\n' ...
'    u_r = u_cmd_r;\n' ...
'end\n' ...
'u_f = max(-umax, min(umax, u_f));\n' ...
'u_r = max(-umax, min(umax, u_r));\n' ...
'end\n'], p.a, p.b, p.u_max, p.C_e);
end

function c = code_coil(p)
c = sprintf([ ...
'function [emf, p_mech] = Faraday_Coil(x_d, mode)\n' ...
'%%#codegen\n' ...
'%% Faraday induction. e = k_e*v_rel. p_mech bounds the recoverable power.\n' ...
'a=%.4f; k_e=%.4f; C_e=%.6f;\n' ...
'vrf = (x_d(5) - a*x_d(6)) - x_d(7);\n' ...
'if mode > 0.5\n' ...
'    emf = k_e*vrf;\n' ...
'    p_mech = C_e*vrf*vrf;\n' ...
'else\n' ...
'    emf = 0; p_mech = 0;\n' ...
'end\n' ...
'end\n'], p.a, p.k_e, p.C_e);
end

function c = code_rectifier(p)
c = sprintf([ ...
'function [v_rect, i_coil] = Rectifier(emf)\n' ...
'%%#codegen\n' ...
'%% Full-bridge rectifier: two diode drops in the conduction path.\n' ...
'Vd=%.4f; Rc=%.4f; Rl=%.4f;\n' ...
'v_rect = max(0, abs(emf) - 2*Vd);\n' ...
'i_coil = v_rect/(Rc + Rl);\n' ...
'end\n'], p.V_diode, p.R_coil, p.R_load);
end

function c = code_lcfilter(p)
c = sprintf([ ...
'function [v_cap, i_ind] = LC_Filter(v_rect, mode)\n' ...
'%%#codegen\n' ...
'%% LC low-pass + capacitor bank. SEMI-IMPLICIT Euler (forward Euler is\n' ...
'%% unstable for this lightly damped LC).\n' ...
'persistent iL vC\n' ...
'Lf=%.6f; Cf=%.8f; Rc=%.4f; Rl=%.4f; dt=%.6f;\n' ...
'if isempty(iL)\n' ...
'    iL = 0; vC = 0;\n' ...
'end\n' ...
'if mode > 0.5\n' ...
'    iL = iL + dt*(v_rect - vC - iL*Rc)/Lf;\n' ...
'    vC = vC + dt*(iL - vC/Rl)/Cf;\n' ...
'else\n' ...
'    vC = vC*exp(-dt/(Rl*Cf));\n' ...
'    iL = iL*exp(-dt*Rc/Lf);\n' ...
'end\n' ...
'v_cap = vC; i_ind = iL;\n' ...
'end\n'], p.L_filter, p.C_filter, p.R_coil, p.R_load, p.dt);
end

function c = code_boost(p)
c = sprintf([ ...
'function [v_bus, p_out] = Boost_Converter(v_cap, i_coil, p_mech)\n' ...
'%%#codegen\n' ...
'%% Steps voltage up. Cannot create power: bounded by p_mech.\n' ...
'D=%.4f; Rl=%.4f; eta_r=%.4f; eta_b=%.4f;\n' ...
'v_bus = v_cap/(1 - D);\n' ...
'p_elec = i_coil*i_coil*Rl;\n' ...
'p_out = min(p_elec*eta_r*eta_b, p_mech);\n' ...
'end\n'], p.D_boost, p.R_load, p.eta_rect, p.eta_boost);
end

function c = code_battery(p)
c = sprintf([ ...
'function soc = Battery_SoC(p_out, u_f, x_d, mode)\n' ...
'%%#codegen\n' ...
'%% Coulomb counting. Charges in ECO, discharges in COMFORT.\n' ...
'persistent s\n' ...
'a=%.4f; dt=%.6f; capj=%.4f; eta_a=%.4f;\n' ...
'if isempty(s)\n' ...
'    s = 0.5;\n' ...
'end\n' ...
'vrf = (x_d(5) - a*x_d(6)) - x_d(7);\n' ...
'if mode > 0.5\n' ...
'    s = min(1, s + p_out*dt/capj);\n' ...
'else\n' ...
'    s = max(0, s - abs(u_f*vrf)/eta_a*dt/capj);\n' ...
'end\n' ...
'soc = s;\n' ...
'end\n'], p.a, p.dt, p.cap_batt_j, p.eta_act);
end
